-   repo: git@github.com:yashmehrotra/commit-strip-dl.git
    sha: f30f08b7c02bc4cbe614de32ec042f5e95722357
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: flake8
