this = 23
string = 'aaaaaaaaaaaaaaaasddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaaaaaaaaad'
stng = 'aaaaaaaaaaaaaaaasddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddaaaaaaaaaaaaad'
